trigger:
  branches:
    include:
      - main

parameters:
  - name: Environment
    type: string
    default: dev
    values:
      - dev
      - staging
      - prod
  - name: namespace
    type: string
    default: default
    values:
      - elearn-ui
      - elearn-backend
      
variables:
  - group: AKS-Config-{{ parameters.Environment }} # <-- Link your variable group here
    TAG: $(Build.BuildId)
 
stages:
- stage: BuildAndPush
  displayName: "Build Docker Image and Push to ACR"
  jobs:
  - job: Build
    displayName: "Build & Push Docker Image"
    pool: todo-app-infra
    steps:
    - task: Checkout@1

    # Login to ACR
    - task: AzureCLI@2
      displayName: 'Login to ACR'
      inputs:
        azureSubscription: 'unicsolutions'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(ACR_NAME)   #varible group

    # Build Docker Image
    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG) .
      displayName: 'Build Docker Image'

    # Push Docker Image to ACR
    - script: |
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(TAG)
      displayName: 'Push Docker Image to ACR'

- stage: DeployToAKS
  displayName: "Deploy to AKS"
  dependsOn: BuildAndPush
  jobs:  
  - deployment: DeployToAKS
    displayName: 'Deploying to AKS'
    environment: 
      name: {{ parameters.Environment }} 
      resourceType: Kubernetes
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@1
            displayName: Deploy to AKS
            inputs:
              action: deploy
              kubernetesServiceConnection: 'aks-service-connection'
              namespace: {{ parameters.namespace }} # deployment in multiple environment throguh this parameter
              manifests: |
                manifests/deployment.yaml
                manifests/service.yaml